# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a9e677d5e2aa99f95410f97cc60babe467400a3df4faf223773c8c5bc92f46692c175fc643aafa8f66e64764776fd5803d706142e5743c4571ee3e91182d576

test:
  secret_key_base: 2e5d95dacc435abff3a377178668cad586e21251a0c4652c22c6277a2878c1776809c8432386acf7d940659e6fd4b2d731145a54e1bfd88f3ca9443638772000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
